# Production monitoring configuration for EKS
kube-prometheus-stack:
  enabled: true

  # Prometheus configuration
  prometheus:
    enabled: true

    prometheusSpec:
      # Retention settings for development
      retention: 7d
      retentionSize: 20GiB

      # Storage configuration
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 30Gi

      # Resource configuration for t3.micro nodes
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi

      # Service monitor configuration
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false

      # Additional scrape configs for our services
      additionalScrapeConfigs:
        - job_name: "task-manager"
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - task-manager
          relabel_configs:
            - source_labels:
                [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels:
                [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels:
                [
                  __address__,
                  __meta_kubernetes_pod_annotation_prometheus_io_port,
                ]
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: ${1}:${2}
              target_label: __address__

      # Allow scheduling on GitHub runner node
      tolerations:
        - key: github-runner
          operator: Equal
          value: "true"
          effect: NoSchedule

  # Grafana configuration
  grafana:
    enabled: true

    # Admin credentials
    adminPassword: "admin123"

    # Storage configuration
    persistence:
      enabled: true
      storageClassName: gp2
      size: 10Gi

    # Resource configuration for t3.micro nodes
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

    # Allow scheduling on GitHub runner node
    tolerations:
      - key: github-runner
        operator: Equal
        value: "true"
        effect: NoSchedule

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Default dashboards
    defaultDashboardsEnabled: true

    # Additional dashboards
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        task-manager:
          gnetId: 7587
          revision: 1
          datasource: Prometheus

  # Alertmanager - disabled for development
  alertmanager:
    enabled: false

  # Node Exporter configuration
  nodeExporter:
    enabled: true
    tolerations:
      - key: github-runner
        operator: Equal
        value: "true"
        effect: NoSchedule
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

  # Kube State Metrics configuration
  kubeStateMetrics:
    enabled: true
    tolerations:
      - key: github-runner
        operator: Equal
        value: "true"
        effect: NoSchedule
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

  # Prometheus Operator configuration
  prometheusOperator:
    enabled: true
    tolerations:
      - key: github-runner
        operator: Equal
        value: "true"
        effect: NoSchedule
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi

    # Admission webhooks configuration
    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
        tolerations:
          - key: github-runner
            operator: Equal
            value: "true"
            effect: NoSchedule

# Loki-stack - disabled to save resources
loki-stack:
  enabled: false
