apiVersion: v2
name: task-manager
description: A Helm chart for Task Manager FastAPI application
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - task-manager
  - fastapi
  - api
  - postgresql

home: https://github.com/corentinlevet/epitech-iac-team4
sources:
  - https://github.com/corentinlevet/epitech-iac-team4

maintainers:
  - name: Team 4
    email: corentin.levet@epitech.eu
