# Custom values for EKS deployment
replicaCount: 1

image:
  repository: 758888582253.dkr.ecr.us-east-1.amazonaws.com/task-manager
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: false # We'll use LoadBalancer for direct access

# Database configuration - disable default database secret
database:
  secretName: "" # Empty to disable default secret reference

# Environment variables
env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: task-manager-db
        key: DATABASE_URL
  - name: LOG_LEVEL
    value: "INFO"
  - name: ENVIRONMENT
    value: "production"
  - name: API_HOST
    value: "0.0.0.0"
  - name: API_PORT
    value: "8000"

# Resource configuration for t3.micro nodes
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Node selector for application nodes - explicitly disable
nodeSelector: null

# Add tolerations to allow scheduling on github-runner nodes
tolerations:
  - key: "github-runner"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# Probes
livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
